### PR TITLE
adds demo code and sample files/generator

### PR DESCRIPTION
**Pull request by Nolan-Little**
Thursday nights demo. Happy to take feedback on additions and/or changes.

### CODE REVIEW

**Comment by jeff-dillon** [comment]
I really liked the demo - great job! 

My only comment on merging the pull request is a question: how do we want to organize the modules? Currently, there is an empty module called "importing data". I think the importing data module was stubbed out by JR along with a lot of other module stubs that are currently empty. Would it make sense to remove all of the empty modules and just add modules one by one as we create the demos?
@white8785 - thoughts?

**Comment by white8785** [comment]
Correct @jeff-dillon , I was stubbing those out to match each week's class, but that's changed so I'm happy to clean those up and add a new module as we create.

@Nolan-Little , if you want to clean those up in this commit awesome, or I can after you push.

**Review by white8785 — APPROVED** [review]
lgtm

**Comment by jeff-dillon** [comment]
Cool. Sounds like we're good to go. I'll create my pull request for my cleaning demo once this is merged and the stubs are removed.

**Pull request merged**
